### ISSUE TITLE
Language Setup

### ISSUE THREAD

**Issue by TheMusiqBoi** [utarwyn/discord-tictactoe#12]
Hi! The bot works perfectly but, it is showing all messages in French. How do I change the language to English? Please help

**Comment by utarwyn** [comment]
Hello @TheMusiqBoi, it depends on how you run the bot.

With NodeJS, you just have to change the `language` config value: (**"en"** for example)
```js
new TicTacToe({
  language: 'en',
}); 
```

With Docker, you can use the environment variable or the config file.
More are explained in the [README.md file](https://github.com/utarwyn/discord-tictactoe/blob/master/README.md).

You can find all available languages here:
https://github.com/utarwyn/discord-tictactoe/tree/master/config/locales

**Comment by TheMusiqBoi** [comment]
Thank you so much, you're a god!

**Comment by utarwyn** [comment]
Happy to see that your problem has been solved! So you can close the issue if all works fine now :+1:
