### ISSUE TITLE
 *ttt @everyone is causing spam

### ISSUE THREAD

**Issue by anjannair** [utarwyn/discord-tictactoe#13]
When a particular user uses `*ttt @everyone` or `*ttt @here` the bot replies and tags `@everyone` or `@here`. It causes spam as the user then deletes his message. Could you fix that? So it should reply saying `You can't mention that` or something like that?

**Comment by utarwyn** [comment]
Hello, you are true, I didn't think about that possibility! I will fix that

**Comment by utarwyn** [comment]
In order not to change the code completely and to avoid modifying the language file, I have only **removed the ability for the bot to use specific mentions** (`here` and `everyone`). Is this enough?

![image](https://user-images.githubusercontent.com/9255967/97119090-391b3f00-170e-11eb-9641-8045a3a8b180.png)

**Comment by anjannair** [comment]
Hey I think it isn't pushed to npmjs or something cause its still giving that error

**Comment by utarwyn** [comment]
Yes I have not released a new version with that fix yet, you need it soon?

**Comment by anjannair** [comment]
Naah take your time. In the mean time I changed your node_module in my repo to avoid spam.

**Comment by anjannair** [comment]
Can I get a timeframe as to when the update will be pushed?

**Comment by utarwyn** [comment]
Hello @anjannair,
I have just published a new version (**v2.0.7**) on NPM with the fix.
You can find out the changelog here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v2.0.7

Best regards

**Comment by anjannair** [comment]
Thank you! Issue is fixed!

**Comment by anjannair** [comment]
![20201106_182026.jpg](https://user-images.githubusercontent.com/22571613/98368151-dd7d7980-205c-11eb-8993-ca7d2527787d.jpg)

Another spam event which makes the bot mention everyone

**Comment by anjannair** [comment]
Why not just mention the users username and discriminator only instead of tagging him

**Comment by utarwyn** [comment]
uhhh ok, your members have found another bypass... I will try to remove mentions when opponent cannot be find.

**Comment by utarwyn** [comment]
I have removed member mention in that message. So no more problem with that! 😄 
![image](https://user-images.githubusercontent.com/9255967/102422614-74980280-4007-11eb-850d-77a3f5b1f1c3.png)

**Comment by utarwyn** [comment]
I have just released 2.0.8 to fix the issue! :smile: 
https://github.com/utarwyn/discord-tictactoe/releases/tag/v2.0.8
