### ISSUE TITLE
Repeating tic tac toe message

### ISSUE THREAD

**Issue by JoepTM** [utarwyn/discord-tictactoe#15]
If i run the command !ttt it repeats the game message 3 times.

![image](https://user-images.githubusercontent.com/66672754/98416049-b041c300-207e-11eb-8a27-582d944bdb6b.png)

this is my code, maybe there is something wrong with that:

=================================================================================
const TicTacToe = require('discord-tictactoe');
const Discord = require('discord.js');
const client = new Discord.Client();
const token = <bot token>;

new TicTacToe({
  language: 'en',
  command: '!ttt'
}, client);

client.login(token);

**Comment by utarwyn** [comment]
Hello, I have never seen that issue before... are you sure that this code is run only one time by your bot (by using a `console.log` or something like that)? Otherwise I will try to identify why does this occur, but that's strange.

**Comment by JoepTM** [comment]
I only laiunch it ones but it could be that someone stole bot token. I'll refresh my token then.

**Comment by JoepTM** [comment]
![image](https://user-images.githubusercontent.com/66672754/98439980-17e72500-20f6-11eb-8a57-76b9cc999dcd.png)
that worked

**Comment by utarwyn** [comment]
oh well, great news!
