### ISSUE TITLE
Discord.js v13

### ISSUE THREAD

**Issue by Inferno1679** [utarwyn/discord-tictactoe#155]
Hello, when i install using npm it seems to use discord.js@12.5.3 could you make the npm package have djs v13 ?

**Comment by utarwyn** [comment]
Hello, the latest release **(v2.2.0)** still uses discord.js 12.5.3 for compatibility reasons. A new major version of the module is still under work to support **discord.js v13** with new API features like Discord buttons. It will available as soon as possible. Check the issue to have more info on it: #48.

**Comment by utarwyn** [comment]
Version 3 of the module is now out! You can use `npm i discord-tictactoe@^3` to install it.
More info on the release here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v3.0.0
