### ISSUE TITLE
not sure how to use the bot? and how to even set it up

### ISSUE THREAD

**Issue by husosh** [utarwyn/discord-tictactoe#16]
ive never seen a bot in index.ts usually i just do node index.js, sorry im an amateur

**Comment by anjannair** [comment]
@husosh what do you mean? Do you want to use this as an independent bot? Or in your pre-built bot?

**Comment by utarwyn** [comment]
Hello @husosh, you can find an example on how to use it here **(you need to install NodeJS)**:
https://github.com/utarwyn/discord-tictactoe#use-it-in-your-project

You can start it by using your own bot or a new one.

**Comment by husosh** [comment]
Independent

**Comment by husosh** [comment]
I don’t know how to even go use the bot as independent like I’m so lost 😂

**Comment by husosh** [comment]
can someone add me on discord and help me please!

**Comment by husosh** [comment]
@utarwyn

**Comment by utarwyn** [comment]
You must know how to write NodeJS scripts first. We can discuss this on Discord yes! **Utarwyn#1334**

**Comment by husosh** [comment]
@utarwyn i sent you a friend request on discord

**Comment by husosh** [comment]
hey @utarwyn Please check discord dms

**Comment by utarwyn** [comment]
**Issue resolved on Discord** :+1: For those who also need help, do not hesitate to contact me: **Utarwyn#1334**!

Also a detailed list of steps to follow to install it quickly using **npm**:
1. Install at least **Node.js 12** (https://nodejs.org/en/download)
2. Create a new folder with the name you want
3. Type command `npm init -y` inside this folder to initialize a Node project
4. Type command `npm i discord-tictactoe` to install the bot
5. Create a file bot.js with the content of the README, for example:
```js
const TicTacToe = require('discord-tictactoe');
const bot = new TicTacToe({
  clientId: 'YOUR_CLIENT_ID',
  token: 'YOUR_BOT_USER_TOKEN',
  language: 'en',
  command: '!ttt'
}); 
bot.connect().catch(() => console.error("Cannot connect TicTacToe bot"));
```

6. If you don't have a token, create a new application on Discord website (https://discord.com/developers/applications)
7. You can start the bot with the command `node bot.js`
