### ISSUE TITLE
Bot is not deploying slash commands

### ISSUE THREAD

**Issue by ilikecheesybread** [utarwyn/discord-tictactoe#165]
Whenever I try to deploy slash commands, the bot doesn't respond at all. I'm guild admin but when I type `?tttdeploy`, nothing happens.
The code I'm using is:
```const TicTacToe = require('discord-tictactoe');
new TicTacToe({ language: 'en' })
   .login('my token is here')
   .then(() => console.log('TicTacToe bot is ready to be used.'));
```
Console does log `TicTacToe bot is ready to be used.` but nothing happens when I try to deploy. Any help would be much appreciated.

**Comment by ilikecheesybread** [comment]
Sorry, turns out when I was inviting it I didn't include `applications.commands` in my invite link. :/

**Comment by utarwyn** [comment]
Hello, sorry I did not have updated the README to describe which permissions are required to use commands with the module. I will do that!
