### ISSUE TITLE
discord-tictactoe@^3 doesn't exist

### ISSUE THREAD

**Issue by MinhCrafters** [utarwyn/discord-tictactoe#166]
![image](https://user-images.githubusercontent.com/59521026/151683792-ed7c14ec-83e4-4e5e-9624-1a4e86128085.png)
it said that discord-tictactoe@^3 doesn't exist
is it just me or the author haven't uploaded v3 of the package yet?

**Comment by utarwyn** [comment]
Hello, indeed I have updated the README file for the next version but this one is not released yet. I had planned to release it this week, but I have some bug fixes to do before.

Sorry for that.. you have to use version 2 of the module for now. I'll keep you informed on my progress on bug fixes.

**Comment by MinhCrafters** [comment]
Oh, OK... but can I install the github version of this package? I tried but it said that no module named tictactoe.js in dist folder.

**Comment by utarwyn** [comment]
If you want to install it directly from the Github repo using npm, you can use following commands:
```
npm install https://github.com/utarwyn/discord-tictactoe/archive/next.tar.gz
cd node_modules/discord-tictactoe
npm install
npm run build
```

:warning: **Keep in mind that this method should only be used for testing purposes, as you are using latest development version of the module.**

**Comment by MinhCrafters** [comment]
It returned this...
![image](https://user-images.githubusercontent.com/59521026/153546488-961ea8b6-956e-4354-bc1c-4e9aea997a5d.png)

**Comment by utarwyn** [comment]
Version 3 of the module is now out! You can use `npm i discord-tictactoe@^3` to install it.
More info on the release here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v3.0.0
