### ISSUE TITLE
Can you add the text support too?

### ISSUE THREAD

**Issue by corropted** [utarwyn/discord-tictactoe#181]
Allow us to choose text support or slash command  support

**Comment by utarwyn** [comment]
Hello @corropted! You can already use both slash and text command, or just one of them. You can check this wiki page to have more info about it: https://github.com/utarwyn/discord-tictactoe/wiki/Using-slash-command-in-V3#what-about-the-text-command

**Comment by CoDe-er1** [comment]
Hello @utarwyn as you already told me about text cmd is supported but i still didn't understand how could i actually use after reading doc? Would you please explain me how could i use text cmd too ?

**Comment by utarwyn** [comment]
I am sorry that the wiki is not comprehensive enough. If you look [into the example configuration file](https://github.com/utarwyn/discord-tictactoe/blob/d3b2e8e7458fe46420aba8b784afffeba815665f/config/config.example.json), you can see that two values named `command` and `textCommand` are configurable using **version 3+**.

- **"command"** is the name of the slash command (defaults to `tictactoe`)
- **"textCommand"** is the name of the text command (no default value)

You can fill both values or one of them based on what you need. An empty value means **"Desactivated"**.

#### First example: no slash command, only a text command
```json
{
  "command": "",
  "textCommand": "-tictactoe"
}
```

#### Second example: both slash and text commands
```json
{
  "command": "tictactoe",
  "textCommand": "!ttt"
}
```

**Comment by CoDe-er1** [comment]
Just a one more question can't i use the textcommand with command handler ?! And can you make a textcommand hander too like for interaction

**Comment by utarwyn** [comment]
Hello, yes you can use method `handleMessage` to handle custom messages too 😄
You can find an example in the wiki: https://github.com/utarwyn/discord-tictactoe/wiki/Usage-examples-with-Node.js#handle-messages-by-your-own
