### ISSUE TITLE
The bot cannot handle 2 games at once.

### ISSUE THREAD

**Issue by eightless** [utarwyn/discord-tictactoe#191]
Using Slash Commands, custom handler.

When there is already a game, and someone executes the slash command, it doesn't work. 

I suppose the bot cannot handle more than one games at once and this should be fixed.

**Comment by CyberJack773** [comment]
ikr

**Comment by utarwyn** [comment]
Hello! By default, two games cannot be started simultaneously in a same channel. This is a "normal" limitation to avoid spamming channels with a lot of gameboards. **But** you can allow this behavior by defining configuration `simultaneousGames` to **"true"**:

https://github.com/utarwyn/discord-tictactoe/blob/f24b1dadcd0e83fa8f969f53583b758e1e1b725e/config/config.example.json#L12

Check this issue comment to have more detail on it: https://github.com/utarwyn/discord-tictactoe/issues/53#issuecomment-974945275

**Comment by AriaFantom** [comment]
but that enable A.I you can't play with other player ... I will prefer some type of caching to be used in it like Redis or something as  extras or Map()

**Comment by utarwyn** [comment]
@AriaFantom Do you have an example of use case? I don't clearly understand your idea..
