### ISSUE TITLE
make it a bit more better looking pls

### ISSUE THREAD

**Issue by CyberJack773** [utarwyn/discord-tictactoe#192]
pls make it so that the buttons get disabled when someone/the ai places and the idle buttons get disabled if someone wins. also use ephemeral messages to tell others they cannot play the game/this is not their turn. ty if u add this

**Comment by CyberJack773** [comment]
@utarwyn can you also add custom emojis?

**Comment by utarwyn** [comment]
@CyberJack773 You can already use custom emojies. Check this issue comment: https://github.com/utarwyn/discord-tictactoe/issues/37#issuecomment-849148125

**Comment by CyberJack773** [comment]
@utarwyn tysm but what about my previous request?

**Comment by utarwyn** [comment]
I find that the rendering of the game board with the buttons disabled does not look very nice.
About ephemeral messages, yes I have to add that 😄

**Comment by CyberJack773** [comment]
But if the buttons aren't disabled ppl will click them and it will say interaction failed

**Comment by CyberJack773** [comment]
@utarwyn can u make it an option?

**Comment by utarwyn** [comment]
Yes why not :+1:
