### ISSUE TITLE
Own bot does not receive events

### ISSUE THREAD

**Issue by Mr-KayJayDee** [utarwyn/discord-tictactoe#203]
Hello, in my code i don't receive the events from the modules.

here is my code : 

```js
const TicTacToe = require('discord-tictactoe');
new TicTacToe({ language: 'fr', command: 'ttt', commandOptionName: "user", }).attach(this.client);
```

The command and tictactoe is fully working
There is nothing else, except the event that we are trying to receive

```js
module.exports = class {
    constructor(client) {
        this.client = client;
    }

    async run(data) {
        console.log(data);
    }
};
```

(when emitting this event with `this.client.emit('win') it is received`)

**Comment by utarwyn** [comment]
Hello! Did you follow [this guide](https://github.com/utarwyn/discord-tictactoe/wiki/Event-handling-system) to listen for internal events? It should works with that piece of code for example:

```typescript
const TicTacToe = require('discord-tictactoe');
const bot = new TicTacToe({ language: 'fr', command: 'ttt', commandOptionName: "user", });

bot.attach(this.client)
bot.on('win', data => {
  console.log(data.winner + ' wins the TicTacToe game!');
  console.log(data.loser + ' loses the TicTacToe game!');
});
```

**Comment by Mr-KayJayDee** [comment]
Hello, yes i tried everything that is in the guide and i didn't manage to get the event.

**Comment by Mr-KayJayDee** [comment]
Will it be possible to emit the events to the discord client ? Instead of the TTT Client ?

**Comment by utarwyn** [comment]
Yes I can work on that :+1: I will also do some tests to understand why the events are not issued.

**Comment by Mr-KayJayDee** [comment]
Hey, again ? any news on this issue ?

**Comment by utarwyn** [comment]
Hello! Sorry I did not have time to deal with this issue, I'll look into it soon

**Comment by utarwyn** [comment]
After few tests, I can confirm that events mentionned in [the wiki](https://github.com/utarwyn/discord-tictactoe/wiki/Event-handling-system#event-list) are fired without issue using versions 2 or 3.

I tried to emit these events on the Discord.js client, but I am not sure about this solution, for two reasons:

- As the module is written in Typescript, there is a predefined list of events on the client, I cannot change it
- I cannot easily get the Discord.js client object, as the module can be used without being directly attached to a client

Which version of the module do you use? Can you post me your code to help me identify the problem?

**Comment by Mr-KayJayDee** [comment]
I think the issue was because there was no events sent to the discord client but only on the TTT one. I saw you made some changes, did they includes events emitted to the actual discord client or not ?

**Comment by utarwyn** [comment]
I don't understand why this is an issue to only send events to the TTT module.. Yesterday's changes do not affect the events.
