### ISSUE TITLE
Improve the interface and customizability 

### ISSUE THREAD

**Issue by eightless** [utarwyn/discord-tictactoe#204]
1. If the bot already is already handling a game and another user executes the command, it should return respond "The bot is already handling another game, please wait for it to end."
2. After a duel has been accepted, it should edit the message to "Loading..." instead of "."
3. If trying to duel a bot, it should respond with "You cannot challenge bots." instead of "you cannot challenge this that user."

Plus, all of the above should be customizable via Object options.

**Comment by utarwyn** [comment]
Version 3.1.0 of the module is now out with the three ideas you have mentionned 👍
More info on the release here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v3.1.0
