### ISSUE TITLE
feat: Message Delete

### ISSUE THREAD

**Issue by udit2303** [utarwyn/discord-tictactoe#26]
Don't delete the message instantly after a game has finished, make an option for this (the contructor options) for duration of message delete (given as null if message should not be deleted maybe)

**Comment by utarwyn** [comment]
Hello! Thank you for this awesome idea :+1:

For now I have only added a boolean configuration key to customize game board message deletion.
By default the game board will not been deleted from version **2.1.0**, like this:
![image](https://user-images.githubusercontent.com/9255967/107858961-0620c680-6e37-11eb-80db-048d7bbe14c3.png)

How do you want me to implement the message deletion delay?

**Comment by utarwyn** [comment]
Hello, I close this issue for now as a large of the request has been added to the module. I don't know how to integrate "deletion delay" for gameboard messages but if you have an idea I'm interested. Feel free to reopen it if needed! :+1:
