### ISSUE TITLE
Limit Game to Channel, German Translation

### ISSUE THREAD

**Issue by Boschman21** [utarwyn/discord-tictactoe#27]
Hi,
i want to implement tic tac toe in my bot and it works as described. But I have some difficulties:
1. I cant use my command handler to trigger the bot, i have to put the code in my main file
2. I cant limit the usage to specific channels, meaning you can trigger tic tac toe in every channel. I tried to limit it by using an if statement, but this did not really work, because it just kinda ignored it.
3. There isnt a german translation. I'd love to help with that

A feature to restrict tic tac toe to specific channels would really help me, because otherwise i had to modify my other commands and mess around with dc channel permissions themselves.

I hope the above does not sound rude, it sometimes happens that people say my english sounds a bit arrogant. But that's really not intended.

I would love to hear from you.

**Comment by utarwyn** [comment]
Hello @Boschman21, thank you for the feedback, much appreciated. :+1: About your different points:

1. Indeed, **you cannot use a custom command handler with the latest stable version *(v2.0.8)***.. a new version will be out soon to allow you to use a custom command handling system. Check more info about it here #21. You will be able to create a game instance in a specific file and use it like in the example I have posted in the quoted issue. Is it what you expected?
2. That feature is not implemented yet, but it's very interesting! In the next version you will be able to use your custom command handling to limit usage in certain channels (you have to code it). But it could be a nice idea to integrate it directly to the module, I can create a new issue for that if you want.
3. As I am not German, I can't translate the module into that language.. but contributions are very much appreciated! You can create a new PR to integrate it directly or just give me the translated file based on the english one, available here: https://github.com/utarwyn/discord-tictactoe/blob/next/config/locales/en.json *(json format)* Thank you!

I'm waiting for your feedback,
Regards

**Comment by Boschman21** [comment]
Thank you for your response. You already helped me out alot. What I was trying to get to work in my main file was something looking like this: 

```
client.on('message', message => {
if (message.content === "!ttt") {
if(message.channel.id !== '819309786906361868'){  
	message.react('⚠️')
	message.reply('Wrong Channel --> <#819309786906361868>')
	.then(message => {
		setTimeout(() => message.delete(), 10000)
	})
	return;
}
const TicTacToe = require('discord-tictactoe');
new TicTacToe({
	language: 'de',
	command: '!ttt'
  }, client)
}});
```

I already deleted it so i had to reconstruct the code, so it may be faulty. Just for you to get an idea what i was trying to do. I intented to only trigger tic-tac-toe if the command was written in a specific channel. If it wasn't, the bot should tell the user and delete the message shortly afterwards. But something weird happened I don't quite understand. Once I started up the bot triggering the command in a wrong channel worked as expected, but as soon as it was triggered in the right one it also showed up in forbidden channels when you put in the command, showing up together with the error message I coded. 
So I am really looking forward to being able to use a custom command handler which will hopefully fix that problem :)
Once this works, all my problems with this great module are resolved. 

___German Translation (de.json):___
```
{
  "duel": {
    "title": ":crossed_swords: Neues Duell",
    "challenge": "{invited} fordert **{initier}** zu einem Duell heraus!",
    "action": "Zum Annehmen reagieren.",
    "expire": ":x: `{invited}` ist nicht zum Match angetreten.",
    "reject": ":x: `{invited}` hat das Match abgelehnt.",
    "unknown-user": "Du kannst diesen User nicht herausfordern."
  },
  "game": {
    "title": ":game_die: `{player1}` **VS** `{player2}`",
    "action": "{player} ist am Zug:",
    "load": "Spiel wird geladen, bitte warten...",
    "end": "Kein Sieger, unentschieden! Nochmal?",
    "win": ":tada: {player} hat gewonnen!",
    "expire": ":x: Spiel ist **abgelaufen**... da war wohl keiner mehr da.",
    "waiting-ai": ":robot: KI ist am Zug, bitte warten...",
    "ai": "KI"
  }
}
```

Tested it locally, should fully work. Thank you for the work you are putting in this. I really appreciate it!

**Comment by utarwyn** [comment]
Thank you for your complete feedback. I will integrate your language file this evening and release the new version **2.1.0** with the support of custom command handling and a some new game options.

About the source code you have posted, it will be simpler to integrate the module, for example by using this source code:
```js
const TicTacToe = require('discord-tictactoe');
const game = new TicTacToe({
  language: 'de',
  // command: '!ttt': you can remove that config key as your are using a custom handler
});

client.on('message', message => {
  if (message.content === "!ttt") {
    if (message.channel.id !== '819309786906361868') {
      // all the magic is here, you just have to call the method with the message object
      game.handleMessage(message);
    } else {
      message.react('⚠️')
      message.reply('Wrong Channel --> <#819309786906361868>')
        .then(message => {
          setTimeout(() => message.delete(), 10000)
        })
    }
  }
});
```

**Comment by utarwyn** [comment]
The new version **v2.1.0** has been released just now! Check with my above example if all working fine for you. In that case I let you close this issue. Hope that all will be ok :+1:

**Comment by Boschman21** [comment]
Thank you so much! Everything is working fine now using your code!

**Comment by Boschman21** [comment]
I just stumbled upon a few things that are important: I actually made a mistake in the translation in line 4, which I corrected just now, where i accidentally swapped `{invited}` and `**{initier}**`. But it's fine now in the edit. It also sounds better now when you read it.
I also had a problem where you could only play against the AI and not against other users with the above code, but I fixed that myself by simply swapping `if (message.content === "!ttt") {` out with `if (message.content.startsWith("!ttt")) {`. But this is just a problem with the handler. 
I am sorry I didn't double-check :) but I am sure it's fine now.
