### ISSUE TITLE
Add support for discord.js v14

### ISSUE THREAD

**Issue by jebediah47** [utarwyn/discord-tictactoe#287]

**Comment by utarwyn** [comment]
Thank you for the issue! This issue will be resolved by #276

**Comment by jebediah47** [comment]
> Thank you for the issue! This issue will be resolved by #276

when do you think it'll be ready?

**Comment by utarwyn** [comment]
Hello, I still have to find a new way to register slash commands as the issue #292 explains.
But yes, the code is good and I will merge the PR it soon 👍
