### ISSUE TITLE
After the slash command the game don't show up

### ISSUE THREAD

**Issue by AzShad** [utarwyn/discord-tictactoe#288]
Hi,

I use my own bot and use slash commands, and I would like to have this game in my bot.
I create a file for the command : 
```
const TicTacToe = require('discord-tictactoe');
const game = new TicTacToe({ language: "en"});

module.exports = {
    name: "tictactoe",
    description: "Start the game tic tac toe !",
    type: "CHAT_INPUT",
    options: [
        {
            name: 'opponent',
            description: 'Who you want to play with',
            type: 'USER',
            required: false
        }
    ],
    run: async ({ interaction }) => {
        game.handleInteraction(interaction);
    },
};
```
But when I do "/tictactoe" on discord, my bot show anything, just "my bot is thinking..."

Can you help me ?
Thank you !
Best regards

**Comment by utarwyn** [comment]
Hello, which version of **discord.js** do you use? Is the `interaction` variable of type [Interaction](https://discord.js.org/#/docs/main/stable/class/Interaction)?

**Comment by AzShad** [comment]
Thank you for your answer !
Sorry I didn't see.
my discord js version is 13.6.0
When I use the debug mode -> interaction: undefined

Ty

**Comment by utarwyn** [comment]
Hello @AzShad, so I don't the issue comes from my module: your interaction variable is `undefined` so tictactoe can't deals with it. Which command system are you using in your bot?

**Comment by AzShad** [comment]
I'm a rooky in js, so sorry if I say some mistake.
I use the commandHandler
I can share you my github if necessary

**Comment by AzShad** [comment]
Well, I think when you tell command system is more like slash command or prefix command.
So for me it's slash command

**Comment by utarwyn** [comment]
Hello, as this issue is not relative to the module I close this issue. But you can contact me on Discord if you want me to help you about the command handler problem: **Utarwyn#1334**. Feel free to reopen it if needed!
