### ISSUE TITLE
Cannot operate because of a lack of permissions in the channel #fosscord

### ISSUE THREAD

**Issue by CE1CECL** [utarwyn/discord-tictactoe#298]
**Describe the bug**
I am trying to load TicTacToe into fosscord, and I get Cannot operate because of a lack of permissions in the channel #fosscord in console, even after changing all discord.js to both fosscord.js or fosscord-gopnik. But I can do !ttt @myself and its will say cannot challenge user message as normal, but nothing else works. I can't even use another person and use !ttt @someone assuming !ttt is my tictactoe command. 

**To Reproduce**
1. Install discord-tictactoe, fosscord-gopnik with npm i
2. change my discord.js to fosscord-gopnik and add to the main bot

const client = new Client({
  disableMentions: "everyone",
  restTimeOffset: 0,
  intents: 3276799,
  http: {
		version: 9,
		agent: {},
        api: 'http://localhost:890/api',
        cdn: 'http://localhost:890',
        invite: 'http://localhost:890/invite',
		template: 'http://localhost:890',
		headers: null,
		scheduledEvent: 'http://localhost:890/events'
  }
});

client.login(TOKEN);
const TicTacToe = require('discord-tictactoe');

new TicTacToe({ language: 'en', token: token, command: "ttt", commandOptionName: "opponent", textCommand: "!ttt", requestExpireTime: 30, requestCooldownTime: 0, requestReactions: true, simultaneousGames: true, gameExpireTime: 30, gameBoardReactions: false, gameBoardDelete: false, gameBoardDisableButtons: false}).attach(client);

3. Run the bot, i did also change things in discord-tictactoe's node_modules folder to the gopnik and change http. You also have to change node:https to node:http if you want to use your own instance on http inside discord.js since gopnik is just a patch for fosscord.

**Expected behavior**
At least reactions should work right now, due to fosscord being in development, since its pretty basic. Tho this config works fine on discord.com with the gopnik module and apis changed pointing to it. 

**Versions**
> Please ensure you are running up to date software before making a bug report. Deprecated versions will not receive support.

discord-tictactoe version:3.0.0
discord.js version:13.9.2
Node.js version:16.16.0

**Comment by CE1CECL** [comment]
I am going to close this because I was getting a little too ahead of myself, 2.0.3 gives a a debug error, of either 
TypeError: Cannot read properties of null (reading 'displayName') or TypeError: Cannot read properties of null (reading 'startsWith')
and fosscord.js related is so buggy right now, you have to currently restart the server to start the bot and do the bot startup quick enough.

**Comment by CE1CECL** [comment]
I got it to somewhat work: https://github.com/Mellick-Bot/discord-tictactoe
There are still bugs here and there, but overall, it is playable!

**Comment by utarwyn** [comment]
Hello! I have not planned to add support for **Fosscord/Spacebar** in a near future. The project is in a very alpha stage, and it is currently rebranded. I think we need to wait for the tool to stabilize (and to have a dedicated JavaScript SDK) and then I might reconsider supporting this platform 😄
