### ISSUE TITLE
Adding this commando project.

### ISSUE THREAD

**Issue by GDWingWangWong** [utarwyn/discord-tictactoe#30]
I’ve been unable to add this to my bot using the commando framework, is this possible or am I doing something wrong?

**Comment by utarwyn** [comment]
Hello, I was not aware of the existence of this project, so i have not tested it yet.
But I will check and get back to you soon!

**Comment by utarwyn** [comment]
I'm back to you with informations, @GDWingWangWong. Even if the support is not native, you can easily add your custom **Commando** command to start a TicTacToe game. Here is a sample of what I have done to make it works:

In your main file:
```javascript
const path = require('path');
const Commando = require('discord.js-commando');

const client = new Commando.Client({
    owner: '...'
});

client.registry
    .registerDefaults()
    .registerCommandsIn(path.join(__dirname, 'commands'));

client.login('MY_BOT_TOKEN');
```

In the file `commands/game/tictactoe.js`:
```javascript
const Command = require("discord.js-commando").Command;
const TicTacToe = require('discord-tictactoe');

module.exports = class TicTacToeCommand extends Command {
    constructor(client) {
        super(client, {
            name: 'tictactoe',
            group: 'commands',
            memberName: 'tictactoe',
            aliases: ['ttt'],
            description: 'Start a tictactoe game'
        })

        this.game = new TicTacToe();
    }

    async run(message) {
        this.game.handleMessage(message);
    }
}
```

You just have to create a TicTacToe instance (you can pass an object with options, see [more info here](https://github.com/utarwyn/discord-tictactoe/blob/next/config/config.example.json)) and use the method `handleMessage(message)` in the `run(message)` method. Is it ok for you?

**Comment by GDWingWangWong** [comment]
It works well! Thanks.
