### ISSUE TITLE
Dueling another user but it's still against the AI

### ISSUE THREAD

**Issue by enffinity69** [utarwyn/discord-tictactoe#318]
![image](https://user-images.githubusercontent.com/111388861/186858612-8624e80e-3ae3-4829-9493-5b7774dbe209.png)

**Comment by utarwyn** [comment]
Hello, I do not reproduce the issue on my Discord server. So I need a little bit more info to take a closer look.
- Which version of the module are you using?
- Do you have changed the config option `commandOptionName` or use a custom command handler?

Thank you for the report.

**Comment by utarwyn** [comment]
You can re-open the issue if you steel have the problem.
