### ISSUE TITLE
Changing Time Values

### ISSUE THREAD

**Issue by ShreyasAyyengar** [utarwyn/discord-tictactoe#35]
I was wondering how to change cooldown times and request expire times. I tried changing the values in the source code itself and then restarting the bot, but that didn't seem to work

![Screenshot 2021-05-04 at 11 46 08 AM](https://user-images.githubusercontent.com/65931801/116958794-51c46d00-acce-11eb-895e-360e4ed7b995.png)

**Comment by utarwyn** [comment]
Hello! Normally you **don't have** to edit source code of the module by your own because you can provide configuration values as described in the README, like this:
```javascript
const TicTacToe = require('discord-tictactoe');
new TicTacToe({ language: 'en', command: '!ttt', requestExpireTime: 5 })
  .login('YOUR_BOT_TOKEN')
  .then(() => console.log('TicTacToe bot is ready to be used.'));
```

Can you try like that? Or maybe can you send me your source code?

**Comment by utarwyn** [comment]
@ShreyasAyyengar Any news on that?

**Comment by utarwyn** [comment]
Re-open the issue if you still have the problem :+1:
