### ISSUE TITLE
Disable Idle Buttons

### ISSUE THREAD

**Issue by CyberJack10000** [utarwyn/discord-tictactoe#354]
When a game ends with the buttons disabled option set to true, the idle/secondary buttons which havent been used throughout the game arent disabled. I hope u add this functionality, I can also provide a sample code which disables all buttons in a message if you wish.

**Comment by CyberJack10000** [comment]
Also by ephemeral mesages i meant that when u or anyother peron clicks a button, it sends the appropriate reply in an ephemeral message

**Comment by utarwyn** [comment]
Hello, I did not actually think about this scenario... I'll work on it! Thanks for the feedback :+1:

**Comment by CyberJack10000** [comment]
Thank you!

**Comment by CyberJack10000** [comment]
Btw can u make it available for v13 too?

**Comment by CyberJack10000** [comment]
Nvm it is v13

**Comment by CyberJack10000** [comment]
Btw @utarwyn how do i enable ephemeral replies

**Comment by utarwyn** [comment]
Yes both versions v13 and v14 of discord.js are supported for now! What do you mean by ephemeral messages?

**Comment by CyberJack10000** [comment]
The hidden messages only you can see

**Comment by CyberJack10000** [comment]
@utarwyn

**Comment by CyberJack10000** [comment]
@utarwyn

**Comment by utarwyn** [comment]
Oh I see, you want to have an option to send all statuses inside ephemeral messages

**Comment by CyberJack10000** [comment]
yes

**Comment by CyberJack10000** [comment]
@utarwyn can u pls inform me when it is done and which version it is?

**Comment by utarwyn** [comment]
Buttons will be disabled when a game is over, from **v3.2.0** (also **v4.1.0**)
Yes I have to work on ephemeral messages, but it will take more time to code. I'll keep you informed in this issue.

**Comment by CyberJack10000** [comment]
Tysm!

**Comment by CyberJack10000** [comment]
Btw i also forgot to add that when the game ends because of someone going idle tge buttons will still be there but disabled when the withdisabled option is set to true also the same thing for the askmessage

**Comment by CyberJack10000** [comment]
@utarwyn

**Comment by utarwyn** [comment]
Yes I have to handle all use cases to disable buttons when not needed anymore 👍

**Comment by CyberJack10000** [comment]
tyty

**Comment by CyberJack773** [comment]
are u done yet?(im just asking to see if ur still alive)

**Comment by Sophan-Developer** [comment]
![image](https://user-images.githubusercontent.com/67356294/203880223-f8d42dd0-06a1-458d-a590-d6f408670afe.png)
Djs v14 doesn't work, When a game ends the buttons doesn't disabled

**Comment by CyberJack10000** [comment]
@utarwyn

**Comment by CyberJack10000** [comment]
@Sophan-Developer i agree on the embed thing but making it an option will be better since many dont want it

**Comment by CyberJack10000** [comment]
Also did u do withButtonsDisabled: true in the config?

**Comment by CyberJack773** [comment]
@utarwyn are you done yet?

**Comment by CyberJack10000** [comment]
@utarwyn?

**Comment by CyberJack10000** [comment]
Sorry if im being a bit impatient

**Comment by CyberJack773** [comment]
@utarwyn?

**Comment by utarwyn** [comment]
Sorry for being inactive on that issue since a long time. I have worked recently on the module to add a level of difficulty of the AI. Disabled buttons will be available in the same version, it's the next thing I have to work onto 😉

**Comment by CyberJack10000** [comment]
Ok tysm

**Comment by CyberJack10000** [comment]
Btw dont forget to send statuses in ephemeral replies

**Comment by CyberJack10000** [comment]
If by any chance you forgot, read the previous messages

**Comment by CyberJack10000** [comment]
@utarwyn

**Comment by CyberJack773** [comment]
@utarwyn i forgot to tell u to add an optio for custom idle button emojis

**Comment by utarwyn** [comment]
Idle button emoji?

**Comment by CyberJack10000** [comment]
Yes like the dashemoji

**Comment by CyberJack10000** [comment]
➖

**Comment by CyberJack773** [comment]
@utarwyn (sorry for ping)

**Comment by CyberJack773** [comment]
that isn't to hard, is it?

**Comment by utarwyn** [comment]
Ugh yes it's not hard I think

**Comment by utarwyn** [comment]
These features are now available in both versions 3.2.0 (discord.js v13) and 4.1.0 (discord.js v14).
- Use configuration key `gameBoardDisableButtons` to disable buttons when needed.
- Use configuration key `gameBoardEmbed` to enable embed also for the game board.

npm project page: https://www.npmjs.com/package/discord-tictactoe
Releases page: https://github.com/utarwyn/discord-tictactoe/releases

**Comment by CyberJack773** [comment]
tysmmmmmmmmmm
