### ISSUE TITLE
Personalized emoji 

### ISSUE THREAD

**Issue by alexni15** [utarwyn/discord-tictactoe#37]
Hello, would it be possible to provide personalized emoji?

**Comment by utarwyn** [comment]
Hello @alexni15, yes of course, it's an awesome idea!

**Comment by utarwyn** [comment]
And.. you can now start a duel between animals, or anything you want! :t-rex: 
![image](https://user-images.githubusercontent.com/9255967/119735611-e1e47500-be7c-11eb-9b79-71e171ccc578.png)

Mentionned commit adds custom emojies support through the configuration. You will be able to use both strings like `:cow:`, `:cat:` or unicode representations of them. Current emojies remain the default ones. Example of a configuration:
```json
{
  "language": "en",
  "command": "-ttt",
  "gameBoardEmojies": [":dog:", ":cat:"]
}
```

It will be released in the next version!

**Comment by alexni15** [comment]
Oh trop cool et merci.
