### ISSUE TITLE
Discord.js v14

### ISSUE THREAD

**Issue by CodeCarbon** [utarwyn/discord-tictactoe#384]
Add support to discord.js v14

**Comment by utarwyn** [comment]
Hello @CodeCarbon, v4.0.0 should support discord.js v14+.
Do you have an error when running your bot?

**Comment by CyberJack773** [comment]
I think he doesnt realize v4.0.0 is v14

**Comment by utarwyn** [comment]
Version 4.1.0 is now available with support of **discord.js v14.7+**.
I hope this one will work for you too. Feel free to reopen this issue if the problem persists.
