### ISSUE TITLE
Embed color

### ISSUE THREAD

**Issue by Liux71** [utarwyn/discord-tictactoe#388]
How can i change the embeds color?

**Comment by utarwyn** [comment]
Hello, you cannot change duel request embed color for now. But I can look into this and add an option for it 👍

**Comment by Liux71** [comment]
and the play embed? can I change it?

**Comment by utarwyn** [comment]
Which version are you using? There is no more embed in latest versions of the module.

**Comment by Liux71** [comment]
oh yeah you are right it doesent have an embed im sorry

**Comment by utarwyn** [comment]
Np 👍 So, is it okay if I make the color of duel request embeds customizable?

**Comment by Liux71** [comment]
yeah it would fit better with the theme of my bot

**Comment by CyberJack10000** [comment]
@utarwyn how about a toggleable and customizable embed in the game

**Comment by utarwyn** [comment]
This feature is now available in both versions **3.2.0** (discord.js v13) and **4.1.0** (discord.js v14).
Use the configuration key `embedColor` to customize color of embeds. (formats: [R, G, B] or "#HEX" or a number)

npm project page: https://www.npmjs.com/package/discord-tictactoe
Releases page: https://github.com/utarwyn/discord-tictactoe/releases
