### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by shootdot** [utarwyn/discord-tictactoe#4]
Hi there
How can I do multiplayer command ?
When I use the command !ttt @user
in console I get this error 
`DiscordAPIError: Cannot send an empty message
    at C:\Users\mdamm\Alpha_1\Alpha_2\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\mdamm\Alpha_1\Alpha_2\node_modules\snekfetch\src\index.js:215:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  path: '/api/v7/channels/708303949945634900/messages',
  code: 50006,
  method: 'POST'
}`

**Comment by utarwyn** [comment]
Have you found a way to solve this issue? Sorry for the delay, I can investigate more if you want. Can you send me the source code you used to import the TicTacToe bot?

**Comment by aman78600** [comment]
I used the source code which you gave in Readme
its the same code and no changes

Please help me solve it

**Comment by utarwyn** [comment]
With the following source code, it works pretty fine on my Discord server: (I jusst have replaced both config keys **clientId** and **token** with ones of my Discord bot)
```javascript
const TicTacToe = require('discord-tictactoe');
const bot = new TicTacToe({
  clientId: 'MY_CLIENT_ID',
  token: 'MY_TOKEN',
  language: 'en',
  command: '!ttt'
}); 
bot.connect().catch(() => console.error("Cannot connect TicTacToe bot"));
```

As the bot sends messages and reactions in the channel, you must give the following permissions to your bot:

- Send messages
- See old messages
- Add reactions

**Comment by aman78600** [comment]
Hi there,
I have put the same code and I have given Admin permissions to the bot,
!ttt works but I can't do multiplayer like !ttt @user  I don't know how to
fix it.
If you have discord you can DM me Shoot.Dot#0641

**Comment by utarwyn** [comment]
Problem solved by private messages on Discord.
