### ISSUE TITLE
Add customizable idle button emoji

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/discord-tictactoe#417]
_Originally posted by @CyberJack773 in https://github.com/utarwyn/discord-tictactoe/issues/354#issuecomment-1382871359_

**Comment by utarwyn** [comment]
@CyberJack773 This feature will be available from v3.2.0: idle emoji can be configured using third element of the configuration array `gameBoardEmojies`. Example: `["🐮", "🐱", "⬛"]`

**Comment by CyberJack773** [comment]
👍

**Comment by utarwyn** [comment]
This feature is now available in both versions **3.2.0** (discord.js v13) and **4.1.0** (discord.js v14).

npm project page: https://www.npmjs.com/package/discord-tictactoe
Releases page: https://github.com/utarwyn/discord-tictactoe/releases
