### ISSUE TITLE
Expire

### ISSUE THREAD

**Issue by CyberJack773** [utarwyn/discord-tictactoe#421]
Where did you handle the expiration msg after game ends? Cause I want to change a few stuffs in the expiration msg

**Comment by utarwyn** [comment]
Hello, the message is located in the locale file under the key `game.expire`:
https://github.com/utarwyn/discord-tictactoe/blob/4521a2520361cbda2882aec7c7b35e78fd49b572/config/locales/en.json#L25

And the message is sent from this part of the code:
https://github.com/utarwyn/discord-tictactoe/blob/4521a2520361cbda2882aec7c7b35e78fd49b572/src/bot/entity/GameBoard.ts#L262-L265

**Comment by CyberJack773** [comment]
how do i make it so that the buttons stay in the msg? I dont want them to be removed and instad they should get disabled

**Comment by utarwyn** [comment]
Use these two options (set "gameBoardDelete" to false and "gameBoardDisableButtons" to true:
https://github.com/utarwyn/discord-tictactoe/blob/4521a2520361cbda2882aec7c7b35e78fd49b572/config/config.example.json#L16-L17

**Comment by CyberJack773** [comment]
no like when the game expires

**Comment by CyberJack773** [comment]
i dont want the buttons to go away

**Comment by CyberJack773** [comment]
cuz im editing the package files and do a few modificatons

**Comment by utarwyn** [comment]
If you want to keep buttons when a game expires, you have to remove the call to `tunnel.end()` because it removes the game board. You should do more or less the same code as when a player wins (update the message instead):
https://github.com/utarwyn/discord-tictactoe/blob/4521a2520361cbda2882aec7c7b35e78fd49b572/src/bot/entity/GameBoard.ts#L246-L247

**Comment by CyberJack773** [comment]
`yield this.createBuilder().withExpireMessage().toMessageOptions();
            this.tunnel.reply?.reactions?.removeAll();
            this.manager.endGame(this);`?

**Comment by CyberJack773** [comment]
yea i cant do it, i dont understand what youve written in the code its too complicated

**Comment by CyberJack773** [comment]
@utarwyn what shoukd i do cause to do this.update you need interaction which i dont have

**Comment by CyberJack773** [comment]
@utarwyn is there a way to edit tunnel so it doesnt removes buttons?
