### ISSUE TITLE
The command can be used to mention everyone

### ISSUE THREAD

**Issue by loulou133** [utarwyn/discord-tictactoe#43]
The command can be used to mention everyone.
If a person changes nickname in a server and puts for example: `g` @ everyone
The bot can mention everyone
![image](https://user-images.githubusercontent.com/72643424/121698197-0facf900-cace-11eb-9d48-cdbe27a0b98a.png)

**Comment by utarwyn** [comment]
Hello @loulou133, It appears that its a case that I forgot when working on that problem before.. See more here: #23
I will try to work on a fix which will resolve this annoying bug.. maybe by removing characters ``` and `@` from player nicknames?

**Comment by utarwyn** [comment]
I have used method from **Discord.js** library to remove mentions from a message. I have also removed characters "`" from names. Here is the final result with the fix (linked commit):
![image](https://user-images.githubusercontent.com/9255967/122688554-38936380-d21d-11eb-94a9-2be820c5dd92.png)

I think that its enough to avoid all problems with mentions and special characters.

**Comment by loulou133** [comment]
Thank you ! Did you release the new version of your module to correct this?

**Comment by loulou133** [comment]
Hello @utarwyn ! Thank you ! Did you release the new version of your module to correct this?

**Comment by utarwyn** [comment]
I have just released version **2.1.1** with the fix! Check the full changelog here:
https://github.com/utarwyn/discord-tictactoe/releases/tag/v2.1.1

Update the package with `npm update discord-tictactoe` and you should good to go! 🥳
