### ISSUE TITLE
Accept DuelRequest embed question.

### ISSUE THREAD

**Issue by ravenastar-js** [utarwyn/discord-tictactoe#433]
## the "Accept DuelRequest embed"  still remains in the message even after the user accepts, how to remove?
![](https://i.imgur.com/6YtGueW.gif)

```
NPM package ➤ discord-tictactoe@^3
discord.js ➤ v13.*
node.js ➤ v18.13.0
Module version ➤ v3.*
```
### discord-tictactoe@^3 accept v18 version of node.js or only v16?
> if discord-tictactoe@^3 is not compatible with the v18 version of node.js then maybe the bug of not deleting the "Accept DuelRequest embed" is that

**Comment by utarwyn** [comment]
Bugfix is now available in both versions 3.2.1 (discord.js v13) and 4.1.1 (discord.js v14).
Sorry for the inconvenience..

npm project page: https://www.npmjs.com/package/discord-tictactoe
Releases page: https://github.com/utarwyn/discord-tictactoe/releases
