### ISSUE TITLE
Player Emoji

### ISSUE THREAD

**Issue by CyberJack773** [utarwyn/discord-tictactoe#436]
Display player emoji too with the status of the game like `{emoji} | Its now @user turn!`

**Comment by CyberJack773** [comment]
and also add an option to not remove buttons on game exipiry and change duelrequest filter to this
`const filter = (interaction) => {
            if (interaction.user.id === this.invited.id) return true;
            return interaction.reply({
                content: `Only <@${this.invited.id}> can use these buttons!`,
                ephemeral: true,
            });
        };
        `
and gameboard filter to
`const filter = (interaction) => {
            if (interaction.user.id === this.invited.id) return true;
            return interaction.reply({
                content: `Only <@${this.invited.id}> can use these buttons!`,
                ephemeral: true,
            });
        };
        `

**Comment by CyberJack773** [comment]
const filter = (interaction) => {
            if (interaction.user.id !== currentEntity && (interaction.user.id === this.entities[0].id || interaction.user.id === this.entities[1].id)) return interaction.reply({
                content: `Wait for opponent... (<@${currentEntity}>)`,
                ephemeral: true,
            });
              else if (interaction.user.id !== currentEntity && (interaction.user.id !== this.entities[0].id && interaction.user.id !== this.entities[1].id)) return interaction.reply({
                content: `You cannot use these buttons!`,
                ephemeral: true,
            });
  else if (!this.game.isMoveValid(GameBoard.buttonIdentifierToMove(interaction.customId)) && (interaction.user.id === this.entities[0].id || interaction.user.id === this.entities[1].id)) return interaction.reply({
                content: `You cannot place there!`,
                ephemeral: true,
            });
  else return true;
        };

**Comment by CyberJack773** [comment]
@utarwyn those two codes add ephemeral msgs instead of just showing this interaction failed

**Comment by CyberJack773** [comment]
sorry i had done a mistake i fixed it should work now

**Comment by CyberJack100000** [comment]
@utarwyn read my entire message except the codeblocks please since i have suggested a few more things other than ephemeral messages.
