### ISSUE TITLE
Request an opening for the module to add retrieve some information about the game

### ISSUE THREAD

**Issue by alexni15** [utarwyn/discord-tictactoe#46]
Hello.  I would like to ask you something.  If it's not too hard.  It is possible to have an opening on the module to retrieve certain data such as: if the player is playing against the bot, if he has won or lost against the bot.  If the player is playing against another player which of the players won and which lost and which of the winners and loser.  It's to put on a data base.  I will be using Quick.db as my database.  Thank you

**Comment by utarwyn** [comment]
Hello @alexni15, there is no integrated API for now. But you should look to the **event handling system**: it allows you to execute custom code when an event occurs during a tictactoe game (win, tie, etc.). Check more info here: https://github.com/utarwyn/discord-tictactoe/wiki/Event-handling-system

You can use it to save games data into a database or create a reward system for example.
