### ISSUE TITLE
Custom Command Handler

### ISSUE THREAD

**Issue by 73LeKing** [utarwyn/discord-tictactoe#47]
Im looking to use this as a command instead of using it as a Client.On because I would like to pass through the guild prefix as my bot has custom prefixes. Is there anyway of doing this or is it only available to do through Clinent.On?

**Comment by utarwyn** [comment]
Hello @73LeKing,

In readme file I'm using `client.on('message')` as an example to handle messages, but you can use you own command handling system. The only **mandatory** rule is to use the method `game.handleMessage(message)` with **Discord.js** message object. It will try to get mentionned user in the message to start a game against it (or it will start a game against the AI).

Check the following comment to have an example using **Commando**: https://github.com/utarwyn/discord-tictactoe/issues/30#issuecomment-805030511
If you want a more personalized answer, share sample of your source code and I will guide you.

**Comment by 73LeKing** [comment]
Im so sorry for this lol. Im retarded and typed it wrong when I tried it! It worked, 10/10 Game Btw I Love it!
