### ISSUE TITLE
Support for Discord.js V13

### ISSUE THREAD

**Issue by CarelessInternet** [utarwyn/discord-tictactoe#48]
Any plans for making this compatible with discord.js version 13 that is currently in development? When I try to react to the message, nothing happens.

**Comment by utarwyn** [comment]
Hello! When `discord.js` v13 will be available as a stable release, I will add the support of course :+1:
As this a development release for now, apart from specific cases or testing bots, I think it should not be used for production bots.

Do you need it in a near future? I don't know if we can support both versions easily.

**Comment by CarelessInternet** [comment]
I would like to have it in the future, but I don't need it ASAP. I can wait until v13 becomes a stable release. I don't currently need support for v13, since production code is still written in v12. As for now, I have temporarily disabled the tic-tac-toe command for my bot's development for v13 of discord.js.

**Comment by utarwyn** [comment]
As the **version 13** of discord.js is now out, I started to look into it. But I'm quite disappointed that it only supports Node 16+ which is not a LTS version. My module is intended to be used by all, I can't force all module users to use Node 16 for now. And I don't quite agree with the way the **discord.js** creators think.

Check the discussion on it on their repository: discordjs/discord.js#5119

**BUT** I will try to add support for both v12 and v13 and fix the bug you mentionned.
**AND** I'm waiting for a feedback from the **discord.js** team or the release of Node 16 in LTS (end of 2021).

**Comment by CarelessInternet** [comment]
Ah okay, thanks for the update. I do want to mention one thing I forgot, in case you haven't added it in the prototype; I am listening to interaction events instead of message events, which means that you would have to take in account for both slash commands and/or regular messages.

**Comment by utarwyn** [comment]
I have just writing a new issue on this subject yes! Check it here: #56

**Comment by utarwyn** [comment]
Version 3 of the module is now out with **discord.js v13** support!
More info on the release here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v3.0.0
