### ISSUE TITLE
Localisation Support for Serbian

### ISSUE THREAD

**Issue by net-tech** [utarwyn/discord-tictactoe#527]
Hi there,

I was looking into localising the bot into Serbian (Cyrillic) and Serbian (Latin). Discord does not support these languages in their app settings so I wanted to ask if I'm still allowed to make them in that case or if only languages supported by Discord are allowed to be translated to.

**Comment by utarwyn** [comment]
Hello! I have no problem with languages not yet supported by Discord 😄 
If you'd like to add these languages into discord-tictactoe, I'd be very happy to!

Feel free to open a PR 💯
