### ISSUE TITLE
Can i translate it to other language and push to heroku?

### ISSUE THREAD

**Issue by Phil9424** [utarwyn/discord-tictactoe#6]
Can i translate it to other language and push to heroku?

**Comment by utarwyn** [comment]
Hello! You can, of course, translate the bot to another language. You can find currently supported languages in this folder: https://github.com/utarwyn/discord-tictactoe/tree/master/config/locales Don't hesitate to contribute through a PR to help me!

You can also push the bot to heroku for your personal use. I'd like the bot to be able to be used without installation but it's not up to date yet, so you can use a platform like Heroku to host it.

**Comment by Phil9424** [comment]
Hi. I want to use your bot in my project. And I can't change anything in locales folder in node modules. Because after deployed package in heroki. It is default in English. Cuz heroku download it from npmjs not from my locales. At least can you upload to your GitHub my edited Jason file of locales? It is in my language??
--
Отправлено из Mail.ru для Android вторник, 25 августа 2020г., 05:57 +06:00 от Maxime Malgorn  notifications@github.com :

**Comment by utarwyn** [comment]
You want to use a language that is not supported for now, am I right? Send me your file and I will add it to the repository yes!
But yes indeed you can't use a personal locale. I should maybe work on a way to use a custom language file.

**Comment by Phil9424** [comment]
Yes. Take it. Thank you!
[ru.zip](https://github.com/utarwyn/discord-tictactoe/files/5125978/ru.zip)

**Comment by utarwyn** [comment]
Thank you for the translation! Just one thing, you have not fully translated the value in `game.expire`:
"Игра была досрочно завершена **expired**... Может потому что никто не активил?"

There is still the word "expire".

**Comment by Phil9424** [comment]
I forgot to delete it)

**Comment by Phil9424** [comment]
Just delete this word)

**Comment by Phil9424** [comment]
It is an Russian language

**Comment by utarwyn** [comment]
okay haha thank you :)

**Comment by Phil9424** [comment]
Can I use it now?

**Comment by utarwyn** [comment]
I'm updating the readme and after I will release the 2.0.5 👍

**Comment by Phil9424** [comment]
Thx so much. And last question is. Can I connect it for my currency system to play for currency and connect to db to make an rating?

**Comment by utarwyn** [comment]
hmm not for now but nice idea yep! By using an api method when a user wins for example?

**Comment by Phil9424** [comment]
When user want to play with smbd, bot checks his balance and if check successfull and user has money, bot will check opponent's balance. And if it successfull , game starts and users has pay money. After win of one of them, bot gives money to winner.

**Comment by utarwyn** [comment]
I cannot create an integration as complex as this one, because my bot must be generic (and work for everyone). **BUT** I can create a bunch of methods to check if a player can play, when it wins, etc. Inside them you will you will be able to code your balance checking system, etc.

Is that okay for you? I can create a new issue for that new feature.

**Comment by Phil9424** [comment]
Yep. It will be more helpful!

**Comment by Phil9424** [comment]
Hey. Can we create one more beautiful thing?) We can make it together!

**Comment by utarwyn** [comment]
Why not, I am listening to you!

**Comment by Phil9424** [comment]
I want to create beautiful thing. It's an multiplayer poker. I saw it like: embed, reaction control. Everyone who pressed the reaction will be connected to the game. And bot sends to user's dm his pocket cards. After it, like tictactoe, every player's move and betting a cash. After first round. Bot sends flop card to mesage.guild.channel. and you have 3 buttons. Check bet. Fold. After pressing bet - message collector. And after game. Winner take all money.

**Comment by utarwyn** [comment]
Hmm nice idea yep! Let's discuss that on Discord if you want: `Utarwyn#1334`
The release **2.0.5** is now out: https://www.npmjs.com/package/discord-tictactoe

**Comment by Phil9424** [comment]
Thx. Tomorrow I will write you.

**Comment by utarwyn** [comment]
Have a nice evening! :smile:
