### ISSUE TITLE
Changing language after uploading on Heroku

### ISSUE THREAD

**Issue by Green2157** [utarwyn/discord-tictactoe#63]
Good morning, today I found your package for a game of tic-tac-toe and I really liked it. The only problem is that I would like to be able to play in Polish. After creating the "pl.json" file in the languages folder and translating the whole file, I encountered a problem with uploading it to heroku, because heroku downloads the package directly from npmjs.com, instead of using the files uploaded to "node_modules", so the game is automatically in English, is it possible to add Polish in this case?

Thank you in advance and best regards.

**Comment by utarwyn** [comment]
Hello! Thank you, I'm glad that my module pleases you. If you send me the Polish translation file I can add it to the module :+1:
You can check the english file here to have a list of all messages to be translated:
https://github.com/utarwyn/discord-tictactoe/blob/af3f910882d9c66f4049a0cb6b50a321426af9e8/config/locales/en.json

More overall, it is maybe a good idea to add possibility to use an absolute path targeting a translation file.
What do you think of that?

**Comment by Green2157** [comment]
Good morning, sorry for the late reply. I am sending the file with the Polish translation as an attachment. Thank you for accepting the idea, and as for the suggestion to set your own path to the translation file, I'm definitely in favour, it can fix bugs related to some hosting and generally make it easier to use other languages.

Thank you again and best regards.
[pl.zip](https://github.com/utarwyn/discord-tictactoe/files/7122031/pl.zip)
