### ISSUE TITLE
Not working in my bot

### ISSUE THREAD

**Issue by anjannair** [utarwyn/discord-tictactoe#8]
I added the same code as mentioned in my code. When I created a different bot it worked somehow. Help needed please.

**Comment by utarwyn** [comment]
Hello! Sorry for that problem... Do you have an error when starting it? Do you have more information about the issue?

**Comment by anjannair** [comment]
So first I tried the independent bot code which you mentioned. It worked flawlessly. Next I included the code which you mentioned for integrating to my personal bot. It did not work at all. I replaced the command too with my personal command it did not work.

**Comment by utarwyn** [comment]
**Ugh... It works without error on my computer.**

When using your own bot, you don't have to provide a client id and a token in the TicTacToe options object, like so:
```javascript
const TicTacToe = require('discord-tictactoe');
const Discord = require('discord.js');
const yourBot = new Discord.Client();

new TicTacToe({
  language: 'en',
  command: '!tictactoe'
}, yourBot);

yourBot.login('DISCORD_BOT_TOKEN');
```

What does not work: the command? the bot does not login? an error in the console?

**Comment by PGgamer2** [comment]
For me it works fine.
Remember to `npm install discord-tictactoe`,
include it in your main .js file
`const TicTacToe = require('discord-tictactoe');`
and start it
```
new TicTacToe({
  language: 'en',
  command: '!ttt'
}, CLIENT);
```

If it really doesn't work then send the log and some of your code

**Comment by anjannair** [comment]
Oh man I just realized while using the bot in my main index file I was adding it under the message trigger command instead of leaving it independent

What I was doing:
`bot.on('message', message => {
//my code
}`

How I fixed it: removed the `bot.on...` and just added the code you mentioned in the README file.

Sorry for the trouble. Have a great day
